server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    enabled: false

spring:
  application:
    name: wayd-event
  webflux:
    base-path: /event-service-api
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/wayd-event

jwt:
  secret: very-secret-key

wayd:
  kafka:
    address: localhost:9092
    groupId: event
    producer:
      id: event-producer